import {
  ageRange,
  annualIncomes,
  bodyTypes,
  cities,
  castes,
  companyDepartment,
  skinColor,
  countries,
  disabilities,
  educations,
  ethnicGroup,
  familyStatuses,
  familyValues,
  fathersStatuses,
  hobbies,
  interests,
  languages,
  locations,
  mothersStatuses,
  nativePlaces,
  occupations,
  religions,
  states,
  workingWith,
  religiousBeliefs,
  relationshipStatusItems,
  MIN_AGE,
  MAX_AGE,
  MIN_HEIGHT,
  MAX_HEIGHT,
  heightItems,
} from '@/data/common-data';
import Vue from 'vue';

export const commonDataMixin = Vue.extend({
  data: () => ({
    MIN_AGE,
    MAX_AGE,
    MIN_HEIGHT,
    MAX_HEIGHT,
    hobbiesItems: hobbies,
    bodyTypesItems: bodyTypes,
    interestItems: interests,
    languagesItems: languages,
    skinColorItems: skinColor,
    ethnicGroupItems: ethnicGroup,
    disabilitiesItems: disabilities,
    religionsItems: religions,
    countriesItems: countries,
    ageItems: ageRange,
    educationItems: educations,
    masterDegreeItems: educations.find(e => e.value === 'masters').values,
    bachelorDegreeItems: educations.find(e => e.value === 'bachelors').values,
    companyDepartmentItems: companyDepartment,
    workingWithItems: workingWith,
    occupationItems: occupations,
    annualIncomeItems: annualIncomes,
    locationItems: locations,
    fathersStatusItems: fathersStatuses,
    mothersStatusItems: mothersStatuses,
    stateItems: states,
    cityItems: cities,
    nativePlaceItems: nativePlaces,
    familyValuesItems: familyValues,
    familyStatusItems: familyStatuses,
    casteItems: castes,
    religiousBeliefItems: religiousBeliefs,
    relationshipStatusItems: relationshipStatusItems,
    heightItems: heightItems,
  }),
});
